plugin_repo(
    name = "e2e",
    plugin = "plugin-integration-testing",
    revision="a309d9a984d18c627f160b8ae649ee710bd40c53"
)

plugin_repo(
    name = "cc",
    plugin = "cc-rules",
    revision="v0.3.2"
)

plugin_repo(
  name = "shell",
  revision = "v0.1.2",
)
