name: Golang rules
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: ./pleasew test -p -v notice --log_file plz-out/log/test.log
      - name: Run tests with coverage
        run: ./pleasew cover -p -v notice --nocoverage_report --log_file plz-out/log/test.log
      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: |
            plz-out/log
  release:
    needs: [test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: ./pleasew build -o buildconfig.release:True -p -v notice //package:release_files
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: thought-machine/release-action@master
      - name: Release tool
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: thought-machine/release-action@master
        with:
          version-file: tools/please_go/VERSION
          change-log-file: tools/please_go/ChangeLog
          release-prefix: please-go
          release-files: plz-out/package